# Generated by Django 2.0 on 2017-12-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20171208_1812'),
        ('boards', '0003_topic_views'),
    ]

    operations = [
    ]
